server:
  port: ${AUTH_SERVER_PORT:9000}

payment:
  service:
    host: ${PAYMENT_SERVICE_HOST:payment-service.local}
    port: ${PAYMENT_SERVICE_PORT:8080}

logging:
  level:
    org.springframework.boot.sql.init: DEBUG
    org.springframework.boot.jdbc.init: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health"

spring:
  application:
    name: auth-server

  security:
    oauth2:
      authorizationserver:
        client:
          payment-service:
            token:
              access-token-time-to-live: ${ACCESS_TOKEN_TTL:1h}
              refresh-token-time-to-live: ${REFRESH_TOKEN_TTL:3d}
        jwt:
          jwk-source:
            key-store:
              path: classpath:keystore/keystore.jks
              password: changeit
              alias: auth-server

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:api_gateway_auth_server_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:2Pg8_06Egr}
    driver-class-name: org.postgresql.Driver

  jpa:

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: postgresql
      mode: never
      schema-locations:
        - classpath:oauth2-registered-client-schema.sql
        - classpath:oauth2-authorization-schema.sql
        - classpath:oauth2-authorization-consent-schema.sql