logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter: TRACE
    org.springframework.security.oauth2.client.authentication.OAuth2AuthorizationCodeAuthenticationProvider: TRACE
    org.springframework.security.oauth2.client.web.AuthorizationRequestRepository: TRACE
    org.springframework.security.web.authentication.SimpleUrlAuthenticationFailureHandler: TRACE
    org.springframework.security.web.savedrequest: TRACE
    org.springframework.web.client: DEBUG
    org.springframework.web: DEBUG

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          auth-server:
            provider: auth-server
            client-id: "api-gateway"
            client-secret: "api-gateway-password"
            authorization-grant-type: authorization_code
            redirect-uri: "http://api-gateway.local:8080/custom/oauth2/callback"
            scope: openid, profile
        provider:
          auth-server:
            issuer-uri: http://auth-server.local:9000

      resourceserver:
        jwt:
          issuer-uri: http://auth-server.local:9000

  datasource:
    url: jdbc:postgresql://localhost:5432/api_gateway_db
    username: postgres
    password: 2Pg8_06Egr
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create

      show-sql: false
      properties:
        hibernate:
          format_sql: true